remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Exploration of the Link Between Amount of Protein and Recipe Ratings]
description: [Author: Josh Osofsky]